name: ASP.NET MVC (.NET Framework 4.8) to App Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]  

    runs-on: windows-latest

    env:
      Solution_Name: WebApplicationTest.sln
      Test_Project_Path: WebApplicationTest.Tests/WebApplicationTest.Tests.csproj
      
    steps:
    # チェックアウト
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    # msbuild のセットアップ
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    # NuGet のセットアップ
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0

    # NuGet パッケージの復元
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name
       
    # Build 実行
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ github.workspace }}\publish /p:PrecompileBeforePublish=true /p:EnableUpdateable=false
      env:
        Configuration: ${{ matrix.configuration }}
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    # 成果物のアップロード
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: WebApp
        path: ${{ github.workspace }}\publish
        retention-days: 3
